---
- name: Service in docker-compose
  hosts: all
  become: True

  tasks:

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Reddit service
      docker_service:
        project_name: reddit
        definition:
          version: '3.3'
          services:
            post_db:
              image: mongo
              volumes:
                - post_db:/data/db
              networks:
                - back_net
            ui:
              image: dkharchenko/ui
              ports:
                - 9292:9292/tcp
              networks:
                - front_net
            post:
              image: dkharchenko/post
              networks:
                - front_net
                - back_net
            comment:
              image: dkharchenko/comment
              networks:
                - front_net
                - back_net
          volumes:
            post_db: {}
          networks:
            back_net: {}
            front_net: {}
    
    - name: Monitoring Service
      docker_service:
        project_name: reddit
        definition:
          version: '3.3'
          services:
            prometheus:
              image: dkharchenko/prometheus
              ports:
                - '9090:9090'
              volumes:
                - prometheus_data:/prometheus
              networks:
                - front_net
                - back_net
              command:
                - '--config.file=/etc/prometheus/prometheus.yml'
                - '--storage.tsdb.path=/prometheus'
                - '--storage.tsdb.retention=1d'
            node-exporter:
              image: prom/node-exporter:v0.15.2
              user: root
              volumes:
                - /proc:/host/proc:ro
                - /sys:/host/sys:ro
                - /:/rootfs:ro
              networks:
                - front_net
                - back_net
              command:
                - '--path.procfs=/host/proc'
                - '--path.sysfs=/host/sys'
                - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
            mongo-exporter:
              image: xendera/mongodb-exporter
              networks:
                - front_net
                - back_net
              environment:
                - MONGODB_URL=mongodb://post_db
            cloudprober:
              image: dkharchenko/cloudprober
              networks:
                - front_net
                - back_net
            cadvisor:
              image: google/cadvisor:v0.29.0
              networks:
                - front_net
                - back_net
              volumes:
                - '/:/rootfs:ro'
                - '/var/run:/var/run:rw'
                - '/sys:/sys:ro'
                - '/var/lib/docker/:/var/lib/docker:ro'
              ports:
                - '8080:8080'
            grafana:
              image: dkharchenko/grafana
              networks:
                - front_net
                - back_net
              volumes:
                - grafana_data:/var/lib/grafana
              environment:
                - GF_SECURITY_ADMIN_USER=admin
                - GF_SECURITY_ADMIN_PASSWORD=secret
              depends_on:
                - prometheus
              ports:
                - 3000:3000
            alertmanager:
              image: dkharchenko/alertmanager
              networks:
                - front_net
                - back_net
              command:
                - '--config.file=/etc/alertmanager/config.yml'
              ports:
                - 9093:9093
            telegraf:
              image: dkharchenko/telegraf
              networks:
                - front_net
                - back_net
              ports:
                - 9273:9273
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
          volumes:
            prometheus_data:
            grafana_data:
          networks:
            back_net:
            front_net:
