---
- name: Service in docker-compose
  hosts: all
  become: True

  tasks:

    - name: Docker Service
      docker_service:
        project_name: flask
        definition:
          version: '3.3'
          services:
            post_db:
              image: mongo:${MONGO_VERSION}
              volumes:
                - post_db:/data/db
              networks:
                - back_net
            ui:
              image: ${USERNAME}/ui:${UI_VERSION}
              ports:
                - ${PORT}:9292/tcp
              networks:
                - front_net
            post:
              image: ${USERNAME}/post:${POST_VERSION}
              networks:
                - front_net
                - back_net
            comment:
              image: ${USERNAME}/comment:${COMMENT_VERSION}
              networks:
                - front_net
                - back_net
