---
- name: Service in docker-compose
  hosts: all
  become: True

  tasks:

    - name: Install docker-compose
      pip:
        name: docker-compose

    - name: Docker Service
      docker_service:
        project_name: flask
        definition:
          version: '3.3'
          services:
            post_db:
              image: mongo
              volumes:
                - post_db:/data/db
              networks:
                - back_net
            ui:
              image: dkharchenko/ui
              ports:
                - 9292:9292/tcp
              networks:
                - front_net
            post:
              image: dkharchenko/post
              networks:
                - front_net
                - back_net
            comment:
              image: dkharchenko/comment
              networks:
                - front_net
                - back_net
          volumes:
            post_db: {}
          networks:
            back_net: {}
            front_net: {}
