---
- name: Check && install python and Docker
  hosts: all
  become: true

  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

    - name: Install dependecies for Docker
      apt:
         name: "{{ packages }}"
         update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python-pip

    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker

    - name: Install Docker
      apt:
         name: "docker-ce"
         update_cache: yes

    - name: Install pip docker for module docker_container
      pip:
        name: docker
    
    - name: Ensure Docker is started and enabled at boot
      service:
        name: docker
        state: started
        enabled: yes
