version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.5.4
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.5.4
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"

  zipkin:
    image: openzipkin/zipkin
    networks:
      - front_net
      - back_net 
    ports:
      - "9411:9411"

networks:
  back_net:
  front_net:
